# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

#  config.vm.box = "ubuntu/trusty64"
  
  config.vbguest.auto_update = false
  config.vm.provision "file", source: "~/vagrant/files/git-config", destination: "~/.gitconfig"
  
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/vinaysriramn/assignment-vagrant/main/exercise2/scripts/common.sh?token=GHSAT0AAAAAABTLQOESKG4SHWSDODJSHCF6YSVRIEQ"
 
  config.vm.define "apache" do |apache|
	apache.vm.hostname = "apache-server"
	apache.vm.box="ubuntu/trusty64"
	apache.vm.network "forwarded_port", guest: 80, host: 8081
	apache.vm.network "private_network", ip: "192.168.33.30"
	apache.vm.synced_folder "D:/assignment_vagrant/exercise2/test1/", "/vagrant_data/test1/"
	apache.vm.provision "shell", path: "https://raw.githubusercontent.com/vinaysriramn/assignment-vagrant/main/exercise2/scripts/apache.sh?token=GHSAT0AAAAAABTLQOETE5J2VQRTTHUZSUZUYSVRKAQ"
	apache.vm.provider "virtualbox" do |vb|
		vb.name = "apache-server"
		vb.gui=false
		vb.cpus = 1
		vb.memory = "2048"
	end
  end
 
  
  config.vm.define "db" do |db|
	db.vm.hostname="db-server"
	db.vm.box="ubuntu/trusty64"
	db.vm.network "private_network", ip: "192.168.33.20"
	db.vm.synced_folder "D:/assignment_vagrant/exercise2/test2/", "/vagrant_data/test2/"
	#db.vm.synced_folder "D:\assignment_vagrant\exercise2\", "/vagrant_data/test2"
	db.vm.provision "shell", path: "https://raw.githubusercontent.com/vinaysriramn/assignment-vagrant/main/exercise2/scripts/database.sh?token=GHSAT0AAAAAABTLQOETKOAUGBKE2I3QQSRAYSVRKQA"
	db.vm.provider "virtualbox" do |vb|
		vb.name = "db-server"
		vb.gui="false"
 
		vb.cpus = 2
		vb.memory = "1048"
	end
  end
  
  #config.vm.synced_folder "./data", "/vagrant_data"

end
